import 'package:drift_schemix_generator/drift_schemix_generator.dart';
import 'package:schemix/models.dart';
import 'package:test/test.dart';

// ── Fixtures ──────────────────────────────────────────────────────────────────

const _userClass = ClassInfo(
  name: 'User',
  assetPath: 'lib/user.dart',
  hasSchemix: true,
  tableName: 'users',
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      db: FieldDbInfo(isPrimaryKey: true, autoGenerate: true),
    ),
    FieldInfo(name: 'email', dartType: 'String', isNullable: false),
    FieldInfo(name: 'passwordHash', dartType: 'String', isNullable: false),
    FieldInfo(name: 'deletedAt', dartType: 'DateTime', isNullable: true),
  ],
  ctorParamNames: {'id', 'email', 'passwordHash'},
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = DriftGenerator();
  group('DriftGenerator._shouldGenerate', () {
    test('generates when no skip extension', () {
      const cls = ClassInfo(
        name: 'User',
        assetPath: 'lib/user.dart',
        hasSchemix: true,
      );
      expect(DriftGenerator().shouldRun(cls), isTrue);
    });

    test('suppressed when extensions[drift] == false', () {
      final cls = const ClassInfo(
        name: 'DrizzleOnly',
        assetPath: 'lib/drizzle_only.dart',
        hasSchemix: true,
        extensions: {'drift': false},
      );
      expect(DriftGenerator().shouldRun(cls), isFalse);
    });

    test('skipped for enum', () {
      const cls = ClassInfo(
        name: 'Status',
        assetPath: 'lib/status.dart',
        hasSchemix: true,
        isEnum: true,
      );
      expect(DriftGenerator().shouldRun(cls), isFalse);
    });
  });

  group('DriftGenerator.generateFile — User golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateFile([_userClass], 'lib/user.dart', 'models');
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('contains GENERATED header comment', () {
      expect(output, contains('GENERATED BY SCHEMIX'));
    });

    test('imports drift package', () {
      expect(output, contains("import 'package:drift/drift.dart'"));
    });

    test('imports models package', () {
      expect(output, contains("import 'package:models/models.dart'"));
    });

    test('table class extends Table', () {
      expect(output, contains('class UserTable extends Table'));
    });

    test('has @UseRowClass annotation', () {
      expect(output, contains('@UseRowClass(User'));
    });

    test('generates UUID PK column with clientDefault', () {
      expect(output, contains('clientDefault'));
    });

    test('generates email TextColumn', () {
      expect(output, contains('get email'));
      expect(output, contains("named('email')"));
    });

    test('generates snake_case column name for passwordHash', () {
      expect(output, contains("named('password_hash')"));
    });

    test('generates nullable column for deletedAt', () {
      expect(output, contains('get deletedAt'));
      expect(output, contains('.nullable()'));
    });

    test('tableName override is emitted', () {
      expect(output, contains("String get tableName => 'users'"));
    });
  });

  group('DriftGenerator.generateFile — timestamp injection', () {
    test('enableTimestamps injects createdAt and updatedAt', () {
      const cls = ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        enableTimestamps: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
        ],
      );
      final out = generator.generateFile([cls], 'lib/post.dart', 'models');
      expect(out, contains('createdAt'));
      expect(out, contains('updatedAt'));
    });

    test('enableSoftDelete injects nullable deletedAt', () {
      const cls = ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        enableSoftDelete: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
        ],
      );
      final out = generator.generateFile([cls], 'lib/post.dart', 'models');
      expect(out, contains('deletedAt'));
      expect(out, contains('.nullable()'));
    });
  });

  group('DriftGenerator.generateFile — no eligible classes', () {
    test('returns empty string when no class passes shouldRun', () {
      const cls = ClassInfo(
        name: 'NoTable',
        assetPath: 'lib/no_table.dart',
        hasSchemix: true,
      );
      final out = generator.generateFile([cls], 'lib/no_table.dart', 'models');
      expect(out, isEmpty);
    });
  });
}
