import 'package:drift_schemix_generator/drift_schemix_generator.dart';
import 'package:schemix/models.dart';
import 'package:test/test.dart';

// ── Fixtures ──────────────────────────────────────────────────────────────────

const _userClass = ClassInfo(
  name: 'User',
  assetPath: 'lib/user.dart',
  hasSchemix: true,
  generators: GeneratorFlags(drift: true),
  tableName: 'users',
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      db: FieldDbInfo(isPrimaryKey: true, autoGenerate: true),
    ),
    FieldInfo(name: 'email', dartType: 'String', isNullable: false),
    FieldInfo(name: 'passwordHash', dartType: 'String', isNullable: false),
    FieldInfo(name: 'deletedAt', dartType: 'DateTime', isNullable: true),
  ],
  ctorParamNames: {'id', 'email', 'passwordHash'},
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = DriftGenerator();

  group('DriftGenerator.shouldRun', () {
    test('returns true for drift-enabled non-abstract class', () {
      expect(generator.shouldRun(_userClass), isTrue);
    });

    test('returns false when generators.drift is false', () {
      const cls = ClassInfo(
        name: 'NoDrift',
        assetPath: 'lib/no_drift.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: false),
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for abstract schema', () {
      const cls = ClassInfo(
        name: 'Base',
        assetPath: 'lib/base.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: true),
        abstractSchema: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for embeddable class', () {
      const cls = ClassInfo(
        name: 'Address',
        assetPath: 'lib/address.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: true),
        embeddable: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for enum', () {
      const cls = ClassInfo(
        name: 'Status',
        assetPath: 'lib/status.dart',
        hasSchemix: true,
        isEnum: true,
        generators: GeneratorFlags(drift: true),
      );
      expect(generator.shouldRun(cls), isFalse);
    });
  });

  group('DriftGenerator.generateFile — User golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateFile([_userClass], 'lib/user.dart', 'models');
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('contains GENERATED header comment', () {
      expect(output, contains('GENERATED BY SCHEMIX'));
    });

    test('imports drift package', () {
      expect(output, contains("import 'package:drift/drift.dart'"));
    });

    test('imports models package', () {
      expect(output, contains("import 'package:models/models.dart'"));
    });

    test('table class extends Table', () {
      expect(output, contains('class UserTable extends Table'));
    });

    test('has @UseRowClass annotation', () {
      expect(output, contains('@UseRowClass(User'));
    });

    test('generates UUID PK column with clientDefault', () {
      expect(output, contains('clientDefault'));
    });

    test('generates email TextColumn', () {
      expect(output, contains('get email'));
      expect(output, contains("named('email')"));
    });

    test('generates snake_case column name for passwordHash', () {
      expect(output, contains("named('password_hash')"));
    });

    test('generates nullable column for deletedAt', () {
      expect(output, contains('get deletedAt'));
      expect(output, contains('.nullable()'));
    });

    test('tableName override is emitted', () {
      expect(output, contains("String get tableName => 'users'"));
    });
  });

  group('DriftGenerator.generateFile — timestamp injection', () {
    test('enableTimestamps injects createdAt and updatedAt', () {
      const cls = ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: true),
        enableTimestamps: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
        ],
      );
      final out = generator.generateFile([cls], 'lib/post.dart', 'models');
      expect(out, contains('createdAt'));
      expect(out, contains('updatedAt'));
    });

    test('enableSoftDelete injects nullable deletedAt', () {
      const cls = ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: true),
        enableSoftDelete: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
        ],
      );
      final out = generator.generateFile([cls], 'lib/post.dart', 'models');
      expect(out, contains('deletedAt'));
      expect(out, contains('.nullable()'));
    });
  });

  group('DriftGenerator.generateFile — no eligible classes', () {
    test('returns empty string when no class passes shouldRun', () {
      const cls = ClassInfo(
        name: 'NoTable',
        assetPath: 'lib/no_table.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drift: false),
      );
      final out = generator.generateFile([cls], 'lib/no_table.dart', 'models');
      expect(out, isEmpty);
    });
  });
}
