// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/user/user.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example/schemix.dart';

// ─── User ───────────────────────────────────────────────

@UseRowClass(User, generateInsertable: true)
class UserTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get email => text().named('email')();
  TextColumn get passwordHash => text().named('password_hash')();
  TextColumn get displayName => text().named('display_name').nullable()();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  @override
  String get tableName => 'users';
}