// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/tag/tag.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example_outfolder/schemix.dart';

// ─── Tag ───────────────────────────────────────────────

@UseRowClass(Tag, generateInsertable: true)
class TagTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get name => text().named('name').unique()();
  TextColumn get slug => text().named('slug').unique()();

  @override
  String get tableName => 'tags';
}