// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/profile/profile.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example_infolder/schemix.dart';

// ─── Profile ───────────────────────────────────────────────

@UseRowClass(Profile, generateInsertable: false)
class ProfileTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get userId => text().named('user_id').references(UserTable, #id)();
  TextColumn get website => text().named('website').nullable()();
  TextColumn get phoneNumber => text().named('phone_number').nullable()();
  BoolColumn get isActive => boolean().named('is_active').withDefault(const Constant(true))();
  IntColumn get age => integer().named('age').nullable()();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  @override
  String get tableName => 'profiles';
}