import 'dart:async';


import 'package:build/build.dart';
import 'package:path/path.dart' as p;

import 'logger.dart';
import 'registry.dart';

Builder schemixDartBarrelBuilder(BuilderOptions options) =>
    _SchemixDartBarrelBuilder(options);

final class _SchemixDartBarrelBuilder implements Builder {
  _SchemixDartBarrelBuilder(BuilderOptions options)
      : _outputDir = options.config['output_dir'] as String? ?? 'lib',
        _outputFile = options.config['output_file'] as String? ?? 'schemix.dart';

  final String _outputDir;
  final String _outputFile;

  static final _log = const SchemixLogger('dart_barrel');

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$package$': ['$_outputDir/$_outputFile'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final outputs = buildStep.allowedOutputs.toList();
    if (outputs.isEmpty) {
      _log.buildSkip('$_outputDir/$_outputFile', 'no allowed outputs');
      return;
    }

    final barrelId = outputs.first;

    // Load the registry to find all source paths.
    final registryId = AssetId(buildStep.inputId.package, 'lib/schemix_registry.json');
    if (!await buildStep.canRead(registryId)) {
      _log.buildSkip(barrelId.path, 'schemix_registry.json not found');
      return;
    }

    final registryContent = await buildStep.readAsString(registryId);
    final registry = CrossFileRegistry.fromJson(registryContent);

    final enumPaths = <String>{};
    for (final typeInfo in registry.allEnums) {
      enumPaths.add(typeInfo.sourceAssetPath);
    }

    final modelPaths = <String>{};
    for (final typeInfo in registry.allModels) {
      if (!typeInfo.manualImplementation) {
        modelPaths.add(typeInfo.sourceAssetPath);
      }
    }

    if (enumPaths.isEmpty && modelPaths.isEmpty) {
      _log.buildSkip(barrelId.path, 'no models or enums found in registry');
      return;
    }

    final buf = StringBuffer();
    buf.writeln('// GENERATED BY SCHEMIX — DO NOT EDIT.');
    buf.writeln('// Barrel re-export of all schemix models and enums.');
    buf.writeln();

    final allPaths = {...enumPaths, ...modelPaths}.toList()..sort();
    
    for (final path in allPaths) {
      final rel = p.relative(path, from: _outputDir);
      final importPath = rel.replaceAll(r'\', '/');
      buf.writeln("export '$importPath';");
      
      if (modelPaths.contains(path)) {
        final withoutExt = importPath.substring(0, importPath.length - 5);
        buf.writeln("export '$withoutExt.table.dart';");
        buf.writeln("export '$withoutExt.table.drift.dart';");
      }
    }

    await buildStep.writeAsString(barrelId, buf.toString());
    _log.outputWrite(barrelId.path, 'DartBarrelBuilder');
  }
}
