import 'dart:async';

import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;

import 'logger.dart';

Builder schemixIndexBuilder(BuilderOptions options) =>
    _SchemixIndexBuilder(options);

final class _SchemixIndexBuilder implements Builder {
  const _SchemixIndexBuilder(this._options);
  final BuilderOptions _options;

  static final _log = const SchemixLogger('index');

  static const _barrelDir = 'gen';
  static const _barrelFile = 'schemix.g.ts';

  @override
  Map<String, List<String>> get buildExtensions => const {
    r'$package$': ['gen/schemix.g.ts'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final outputs = buildStep.allowedOutputs.toList();
    if (outputs.isEmpty) {
      _log.buildSkip(_barrelFile, 'no allowed outputs');
      return;
    }

    await _writeBarrel(buildStep, outputs.first);
  }

  Future<void> _writeBarrel(BuildStep buildStep, AssetId outputId) async {
    _log.verbose('>> barrel       | scanning gen/**.g.ts');

    final assets =
        (await buildStep.findAssets(Glob('gen/**.g.ts')).toList())
            .where((a) => !a.path.endsWith(_barrelFile))
            .where((a) => !a.path.endsWith('.drizzle.ts'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    _log.verbose('   found        | ${assets.length} schema files');

    for (final a in assets) {
      _log.verbose('   export       | ${a.path}');
    }

    if (assets.isEmpty) {
      _log.verbose('   barrel       | empty (no @Schemix classes found)');
    }

    final exportLines = assets.map((asset) {
      var rel = p.posix.relative(asset.path, from: _barrelDir);
      if (rel.endsWith('.ts')) rel = rel.substring(0, rel.length - 3);
      if (!rel.startsWith('.')) rel = './$rel';
      return "export * from '$rel';";
    });

    final packageName = _options.config['package_name'] as String? ?? 'schemix';

    final content = [
      '// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.',
      '// Barrel file — re-exports every Zod schema generated from Dart models.',
      '//',
      '// Usage:',
      "//   import { UserSchema, User, BusinessStatus } from '$packageName';",
      '',
      if (assets.isEmpty)
        '// No @Schemix-annotated classes found — barrel is intentionally empty.'
      else
        ...exportLines,
      '',
    ].join('\n');

    _log.outputWrite(outputId.path, 'SchemixIndexBuilder');
    await buildStep.writeAsString(outputId, content);
  }
}
