import 'dart:async';

import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;

import 'logger.dart';

Builder schemixIndexBuilder(BuilderOptions options) =>
    _SchemixIndexBuilder(options);

final class _SchemixIndexBuilder implements Builder {
  _SchemixIndexBuilder(BuilderOptions options)
    : _outputDir = options.config['output_dir'] as String? ?? 'gen',
      _outputFile = options.config['output_file'] as String? ?? 'schemix.g.ts',
      // The glob must match whatever ts_dir + zod_suffix produces.
      // Default: gen/**.g.ts
      _globPattern = options.config['glob_pattern'] as String? ?? 'gen/**.g.ts';

  final String _outputDir;
  final String _outputFile;
  final String _globPattern;

  static final _log = const SchemixLogger('index');

  @override
  Map<String, List<String>> get buildExtensions => {
    r'$package$': ['$_outputDir/$_outputFile'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final outputs = buildStep.allowedOutputs.toList();
    if (outputs.isEmpty) {
      _log.buildSkip('$_outputDir/$_outputFile', 'no allowed outputs');
      return;
    }

    final barrelId = outputs.first;

    final glob = Glob(_globPattern);
    final files = await buildStep
        .findAssets(glob)
        .where((id) => id != barrelId)
        .toList();

    if (files.isEmpty) {
      _log.buildSkip(barrelId.path, 'no matching TS files found');
      return;
    }

    files.sort((a, b) => a.path.compareTo(b.path));

    final buf = StringBuffer();
    buf.writeln('// GENERATED BY SCHEMIX — DO NOT EDIT.');
    buf.writeln('// Barrel re-export of all generated schemas.');
    buf.writeln();

    for (final file in files) {
      // Relative path from the barrel file's directory to each export.
      final rel = p.relative(file.path, from: _outputDir);
      // Strip extension for the import path (.g.ts → .g)
      final importPath = rel.replaceFirst(RegExp(r'\.ts$'), '');
      buf.writeln("export * from './$importPath';");
    }

    await buildStep.writeAsString(barrelId, buf.toString());
    _log.outputWrite(barrelId.path, 'IndexBuilder');
  }
}
