import 'dart:async';
import 'dart:io';

import 'package:build/build.dart';
import 'package:path/path.dart' as p;

import 'logger.dart';
import 'registry.dart';

Builder schemixIndexBuilder(BuilderOptions options) =>
    _SchemixIndexBuilder(options);

final class _SchemixIndexBuilder implements Builder {
  _SchemixIndexBuilder(this._options);

  final BuilderOptions _options;

  static final _log = const SchemixLogger('index');

  @override
  Map<String, List<String>> get buildExtensions => const {
    r'$package$': ['.schemix_index_done'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final outputs = buildStep.allowedOutputs.toList();
    if (outputs.isEmpty) {
      _log.buildSkip('schemix.g.ts', 'no allowed outputs');
      return;
    }

    final outputId = outputs.first;

    final registryId = AssetId(
      buildStep.inputId.package,
      'lib/schemix_registry.json',
    );
    if (!await buildStep.canRead(registryId)) {
      _log.buildSkip('schemix.g.ts', 'registry not found');
      return;
    }

    final registryContent = await buildStep.readAsString(registryId);
    final registry = CrossFileRegistry.fromJson(registryContent);

    final tsDir = registry.options['ts_dir'] as String? ?? 'gen';
    final outputFile = _options.config['output_file'] as String? ?? 'schemix.g.ts';
    final zodSuffix = registry.options['zod_suffix'] as String? ?? '.g';

    final dir = Directory(tsDir);
    if (!dir.existsSync()) {
      _log.buildSkip(outputFile, 'ts directory does not exist');
      return;
    }

    final files = dir.listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('$zodSuffix.ts') || f.path.endsWith('.drizzle.ts'))
        .map((f) => f.path)
        .toList();

    if (files.isEmpty) {
      _log.buildSkip(outputFile, 'no matching TS files found');
      return;
    }

    files.sort();

    final buf = StringBuffer();
    buf.writeln('// GENERATED BY SCHEMIX — DO NOT EDIT.');
    buf.writeln('// Barrel re-export of all generated schemas.');
    buf.writeln();

    for (final filePath in files) {
      // Relative path from the barrel file's directory to each export.
      final rel = p.relative(filePath, from: tsDir);
      // Strip extension for the import path (.g.ts → .g)
      final importPath = rel.replaceFirst(RegExp(r'\.ts$'), '');
      // Ensure posix path separators
      final posixPath = importPath.replaceAll(r'\', '/');
      buf.writeln("export * from './$posixPath';");
    }

    final barrelFile = File(p.join(tsDir, outputFile));
    barrelFile.writeAsStringSync(buf.toString());
    _log.outputWrite(barrelFile.path, 'IndexBuilder');
    
    await buildStep.writeAsString(outputId, '// schemix index completed');
  }
}
