// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/user/user.dart
//
// ignore all

import { jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { posts } from '../post/post.drizzle';
import { profiles } from '../profile/profile.drizzle';

export const users = pgTable('users', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  displayName: text('display_name'),
  metadata: jsonb('metadata'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const usersRelations = relations(users, ({ one, many }) => ({
  posts: many(posts),
  profile: one(profiles, { fields: [users.id], references: [profiles.userId] }),
}));

export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;