// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/profile/profile.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'profile.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Profile _$ProfileFromJson(Map<String, dynamic> json) =>
    Profile(
      id: json['id'] as String,
      userId: json['userId'] as String,
      website: json['website'] as String?,
      phoneNumber: json['phoneNumber'] as String?,
      isActive: json['isActive'] as bool,
      age: json['age'] as int?,
    );

Map<String, dynamic> _$ProfileToJson(Profile instance) =>
    <String, dynamic>{
      'id': instance.id,
      'userId': instance.userId,
      'website': instance.website,
      'phoneNumber': instance.phoneNumber,
      'isActive': instance.isActive,
      'age': instance.age,
    };

Profile _$ProfileCopy(Profile src) =>
    Profile(
      id: src.id,
      userId: src.userId,
      website: src.website,
      phoneNumber: src.phoneNumber,
      isActive: src.isActive,
      age: src.age,
    );
