// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/tag/tag.dart
//
// ignore all

import { pgTable, text } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { postTags } from '../post_tag/post_tag.drizzle';

export const tags = pgTable('tags', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  name: text('name').notNull().unique(),
  slug: text('slug').notNull().unique(),
});

export const tagsRelations = relations(tags, ({ many }) => ({
  posts: many(postTags),
}));

export type TagRow = typeof tags.$inferSelect;
export type NewTagRow = typeof tags.$inferInsert;