builders:
  schemix_scan:
    target: ":schemix_builder"
    import: "package:schemix_builder/builder.dart"
    builder_factories: ["schemixScanBuilder"]
    build_extensions:
      "$package$":
        - "lib/schemix_registry.json"
    auto_apply: dependents
    build_to: cache
    runs_before:
      - "schemix_builder|schemix_file"

  schemix_file:
    target: ":schemix_builder"
    import: "package:schemix_builder/builder.dart"
    builder_factories: ["schemixFileBuilder"]
    build_extensions:
      "^lib/{{}}.dart":
        - "lib/{{}}.schemix.dart"
        - "lib/{{}}.table.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "$package$lib/schemix_registry.json"
    runs_before:
      - "drift_dev"

  schemix_index:
    target: ":schemix_builder"
    import: "package:schemix_builder/builder.dart"
    builder_factories: ["schemixIndexBuilder"]
    build_extensions:
      "$package$":
        - ".schemix_index_done"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "lib/schemix_registry.json"
  schemix_dart_barrel:
    target: ":schemix_builder"
    import: "package:schemix_builder/builder.dart"
    builder_factories: ["schemixDartBarrelBuilder"]
    build_extensions:
      "$package$":
        - "lib/schemix.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "$package$lib/schemix_registry.json"


