// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/product/product.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example/schemix.dart';

// ─── Product ───────────────────────────────────────────────

@UseRowClass(Product, generateInsertable: true)
class ProductTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get name => text().named('name')();
  RealColumn get price => real().named('price')();
  IntColumn get stock => integer().named('stock')();
  TextColumn get type => text().named('type')();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  @override
  String get tableName => 'products';
}