// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/product/product.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'product.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Product _$ProductFromJson(Map<String, dynamic> json) =>
    Product(
      id: json['id'] as String,
      name: json['name'] as String,
      price: json['price'] as double,
      stock: json['stock'] as int,
      type: json['type'] as String,
    );

Map<String, dynamic> _$ProductToJson(Product instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'price': instance.price,
      'stock': instance.stock,
      'type': instance.type,
    };

Product _$ProductCopy(Product src) =>
    Product(
      id: src.id,
      name: src.name,
      price: src.price,
      stock: src.stock,
      type: src.type,
    );
