import 'package:build/build.dart';
import 'package:drizzle_schemix_generator/drizzle_schemix_generator.dart';
import 'package:schemix/schemix.dart';
import 'package:test/test.dart';

// ── Stub TypeGraph ─────────────────────────────────────────────────────────────

final class _StubGraph implements TypeGraph {
  const _StubGraph({this.models = const {}, this.enums = const {}});
  final Set<String> models;
  final Set<String> enums;

  @override
  bool isEnum(String name) => enums.contains(name);
  @override
  bool isModel(String name) => models.contains(name);
  @override
  bool isEmbeddable(String name) => false;
  @override
  TypeInfo? resolve(String name) {
    if (enums.contains(name)) {
      return TypeInfo(
        name: name,
        isEnum: true,
        enumValues: ['a', 'b'],
        sourceAssetPath: 'lib/models.dart',
      );
    }
    if (models.contains(name)) {
      return TypeInfo(
        name: name,
        isEnum: false,
        sourceAssetPath: 'lib/models.dart',
      );
    }
    return null;
  }

  @override
  Set<String> get cyclicTypes => const {};
  @override
  String? relativeImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
  @override
  String? relativeDrizzleImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
}

// ── Fixtures ──────────────────────────────────────────────────────────────────

const _userClass = ClassInfo(
  name: 'User',
  assetPath: 'lib/user.dart',
  hasSchemix: true,
  generators: GeneratorFlags(drizzle: true),
  tableName: 'users',
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      db: FieldDbInfo(isPrimaryKey: true, autoGenerate: true),
    ),
    FieldInfo(name: 'email', dartType: 'String', isNullable: false),
    FieldInfo(name: 'deletedAt', dartType: 'DateTime', isNullable: true),
  ],
);

// ── Stub BuilderOptions ───────────────────────────────────────────────────────

final class _NoOpOptions implements BuilderOptions {
  const _NoOpOptions();
  @override
  Map<String, dynamic> get config => const {};
  @override
  bool get isRoot => true;
  @override
  BuilderOptions overrideWith(BuilderOptions? other) => BuilderOptions(config);
}

GeneratorContext _makeContext([TypeGraph? graph]) => GeneratorContext(
  typeGraph: graph ?? const _StubGraph(enums: {}),
  options: const _NoOpOptions(),
  sourceAssetPath: 'lib/user.dart',
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = DrizzleSchemixGenerator();

  group('DrizzleGenerator.shouldRun', () {
    test('returns true for drizzle-enabled non-abstract class', () {
      expect(generator.shouldRun(_userClass), isTrue);
    });

    test('returns false when generators.drizzle is false', () {
      const cls = ClassInfo(
        name: 'NoDrizzle',
        assetPath: 'lib/no_drizzle.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: false),
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for abstract schema', () {
      const cls = ClassInfo(
        name: 'Base',
        assetPath: 'lib/base.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: true),
        abstractSchema: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for embeddable class', () {
      const cls = ClassInfo(
        name: 'Address',
        assetPath: 'lib/address.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: true),
        embeddable: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for enum', () {
      const cls = ClassInfo(
        name: 'Status',
        assetPath: 'lib/status.dart',
        hasSchemix: true,
        isEnum: true,
        generators: GeneratorFlags(drizzle: true),
      );
      expect(generator.shouldRun(cls), isFalse);
    });
  });

  group('DrizzleGenerator.generate — User golden', () {
    late GeneratorOutput output;

    setUpAll(() {
      output = generator.generate(_userClass, _makeContext());
    });

    test('produces .drizzle.ts extension key', () {
      expect(output.outputs.keys, contains('.drizzle.ts'));
    });

    test('output is non-empty', () {
      expect(output.outputs['.drizzle.ts'], isNotEmpty);
    });

    test('contains GENERATED header', () {
      expect(
        output.outputs['.drizzle.ts'],
        contains('AUTO-GENERATED BY SCHEMIX'),
      );
    });

    test('imports drizzle-orm/pg-core', () {
      expect(
        output.outputs['.drizzle.ts'],
        contains("from 'drizzle-orm/pg-core'"),
      );
    });

    test('imports uuid for auto-generate PK', () {
      expect(output.outputs['.drizzle.ts'], contains("from 'uuid'"));
    });

    test('contains pgTable declaration for users', () {
      expect(output.outputs['.drizzle.ts'], contains("pgTable('users'"));
    });

    test(r'contains $inferSelect type export', () {
      expect(output.outputs['.drizzle.ts'], contains(r'$inferSelect'));
    });

    test(r'contains $inferInsert type export', () {
      expect(output.outputs['.drizzle.ts'], contains(r'$inferInsert'));
    });

    test('nullable deletedAt field has no .notNull()', () {
      final src = output.outputs['.drizzle.ts']!;
      // Find the deletedAt line and verify it lacks .notNull()
      final lines = src.split('\n');
      final deletedAtLine = lines.firstWhere(
        (l) => l.contains('deletedAt'),
        orElse: () => '',
      );
      expect(deletedAtLine, isNot(contains('.notNull()')));
    });
  });

  group('DrizzleGenerator.generate — relations output', () {
    test('BelongsTo relation emits relations block', () {
      const cls = ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: true),
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(
            name: 'userId',
            dartType: 'User',
            isNullable: false,
            relation: FieldRelationInfo(
              kind: RelationKind.belongsTo,
              targetTypeName: 'User',
            ),
          ),
        ],
      );
      final out = generator.generate(
        cls,
        _makeContext(const _StubGraph(models: {'User'})),
      );
      final src = out.outputs['.drizzle.ts']!;
      expect(src, contains("import { relations }"));
      expect(src, contains('relations('));
    });

    test('class with no relations does not import relations', () {
      const cls = ClassInfo(
        name: 'Tag',
        assetPath: 'lib/tag.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: true),
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(name: 'name', dartType: 'String', isNullable: false),
        ],
      );
      final out = generator.generate(cls, _makeContext());
      final src = out.outputs['.drizzle.ts']!;
      expect(src, isNot(contains("import { relations }")));
    });
  });

  group('DrizzleGenerator.generate — no eligible class', () {
    test('returns empty output when shouldRun is false', () {
      const cls = ClassInfo(
        name: 'Internal',
        assetPath: 'lib/internal.dart',
        hasSchemix: true,
        generators: GeneratorFlags(drizzle: false),
      );
      final out = generator.generate(cls, _makeContext());
      expect(out.outputs['.drizzle.ts'], anyOf(isNull, isEmpty));
    });
  });
}
