// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post_tag/post_tag.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example_outfolder/schemix.dart';

// ─── PostTag ───────────────────────────────────────────────

@UseRowClass(PostTag, generateInsertable: false)
class PostTagTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get postId => text().named('post_id').references(PostTable, #id)();
  TextColumn get tagId => text().named('tag_id').references(TagTable, #id)();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  @override
  String get tableName => 'post_tags';

  @override
  List<Set<Column>> get uniqueKeys => [
    {postId, tagId},
  ];
}