// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post_tag/post_tag.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'post_tag.dart';

PostTag _$PostTagFromJson(Map<String, dynamic> json) =>
    PostTag(
      id: json['id'] as String,
      postId: json['postId'] as String,
      tagId: json['tagId'] as String,
      post: json['post'] == null ? null : Post.fromJson(json['post'] as Map<String, dynamic>),
      tag: json['tag'] == null ? null : Tag.fromJson(json['tag'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$PostTagToJson(PostTag instance) =>
    <String, dynamic>{
      'id': instance.id,
      'postId': instance.postId,
      'tagId': instance.tagId,
      'post': instance.post?.toJson(),
      'tag': instance.tag?.toJson(),
    };

PostTag _$PostTagCopy(PostTag src) =>
    PostTag(
      id: src.id,
      postId: src.postId,
      tagId: src.tagId,
      post: src.post,
      tag: src.tag,
    );
