// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/tag/tag.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'tag.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Tag _$TagFromJson(Map<String, dynamic> json) =>
    Tag(
      id: json['id'] as String,
      name: json['name'] as String,
      slug: json['slug'] as String,
    );

Map<String, dynamic> _$TagToJson(Tag instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'slug': instance.slug,
    };

Tag _$TagCopy(Tag src) =>
    Tag(
      id: src.id,
      name: src.name,
      slug: src.slug,
    );
