// Golden test: verifies ZodGenerator.generateForFile output for a User model.

import 'package:build/build.dart';
import 'package:schemix/schemix.dart';
import 'package:test/test.dart';
import 'package:zod_schemix_generator/zod_schemix_generator.dart';

// ── Stub TypeGraph ─────────────────────────────────────────────────────────────

final class _StubGraph implements TypeGraph {
  const _StubGraph({required this.enums, required this.models});
  final Set<String> enums;
  final Set<String> models;

  @override
  bool isEnum(String name) => enums.contains(name);
  @override
  bool isModel(String name) => models.contains(name);
  @override
  bool isEmbeddable(String name) => false;
  @override
  TypeInfo? resolve(String name) => models.contains(name)
      ? TypeInfo(name: name, isEnum: false, sourceAssetPath: 'lib/models.dart')
      : null;
  @override
  Set<String> get cyclicTypes => const {};
  @override
  String? relativeImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
  @override
  String? relativeDrizzleImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;

  @override
  bool canImport(String typeName, String generatorId) => true;
}

final class _NoOpOptions implements BuilderOptions {
  const _NoOpOptions();
  @override
  Map<String, dynamic> get config => const {};
  @override
  bool get isRoot => true;
  @override
  BuilderOptions overrideWith(BuilderOptions? other) => BuilderOptions(config);
}

GeneratorContext _ctx(String path, [TypeGraph? graph]) => GeneratorContext(
  typeGraph: graph ?? const _StubGraph(models: {}, enums: {}),
  options: const _NoOpOptions(),
  sourceAssetPath: path,
);

// ── Fixtures ──────────────────────────────────────────────────────────────────

final _userClass = const ClassInfo(
  name: 'User',
  assetPath: 'lib/models/user.dart',
  hasSchemix: true,
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      validation: FieldValidation(isUuid: true),
    ),
    FieldInfo(
      name: 'email',
      dartType: 'String',
      isNullable: false,
      validation: FieldValidation(isEmail: true),
    ),
    FieldInfo(
      name: 'score',
      dartType: 'int',
      isNullable: true,
      validation: FieldValidation(min: 0, max: 100),
    ),
  ],
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = ZodGenerator();
  group('ZodGenerator.shouldRun', () {
    test('runs for enum (no extensions check needed)', () {
      const cls = ClassInfo(
        name: 'Status',
        assetPath: 'lib/status.dart',
        isEnum: true,
        hasSchemix: true,
      );
      expect(ZodGenerator().shouldRun(cls), isTrue);
    });

    test('runs when hasSchemix and no skip extension', () {
      const cls = ClassInfo(
        name: 'User',
        assetPath: 'lib/user.dart',
        hasSchemix: true,
      );
      expect(ZodGenerator().shouldRun(cls), isTrue);
    });

    test('suppressed when extensions[zod] == false', () {
      final cls = const ClassInfo(
        name: 'ServerOnly',
        assetPath: 'lib/server_only.dart',
        hasSchemix: true,
        extensions: {'zod': false},
      );
      expect(ZodGenerator().shouldRun(cls), isFalse);
    });

    test('skipped when manualImplementation', () {
      const cls = ClassInfo(
        name: 'Manual',
        assetPath: 'lib/manual.dart',
        hasSchemix: true,
        manualImplementation: true,
      );
      expect(ZodGenerator().shouldRun(cls), isFalse);
    });
  });

  group('ZodGenerator.generateForFile — User golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateForFile(
        [_userClass],
        _ctx('lib/models/user.dart'),
      )!;
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('exports UserSchema', () {
      expect(output, contains('UserSchema'));
    });

    test('id field has .uuid() validation', () {
      expect(output, contains('.uuid()'));
    });

    test('email field has .email() validation', () {
      expect(output, contains('.email()'));
    });

    test('nullable score field has .nullish()', () {
      expect(output, contains('.nullish()'));
    });

    test('score has min/max bounds', () {
      expect(output, contains('.gte(0)'));
      expect(output, contains('.lte(100)'));
    });

    test('generated header is present', () {
      expect(output, contains('GENERATED BY SCHEMIX'));
    });
  });

  group('ZodGenerator — skipField behaviour', () {
    test('ZodIgnore field is excluded', () {
      final cls = const ClassInfo(
        name: 'Token',
        assetPath: 'lib/token.dart',
        hasSchemix: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(
            name: 'rawToken',
            dartType: 'String',
            isNullable: false,
            platform: FieldPlatformFlags(zodIgnore: true),
          ),
        ],
      );

      final output = generator.generateForFile(
        [cls],
        _ctx('lib/token.dart'),
      )!;

      expect(output, contains('id'));
      expect(output, isNot(contains('rawToken')));
    });

    test('OfflineOnly field is excluded', () {
      final cls = const ClassInfo(
        name: 'Config',
        assetPath: 'lib/config.dart',
        hasSchemix: true,
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(
            name: 'localCache',
            dartType: 'String',
            isNullable: true,
            sync: FieldSyncInfo(offlineOnly: true),
          ),
        ],
      );

      final output = generator.generateForFile(
        [cls],
        _ctx('lib/config.dart'),
      )!;

      expect(output, isNot(contains('localCache')));
    });
  });
}
