// Golden test: verifies ZodGenerator.generateForFile output for a User model.

import 'package:schemix/models.dart';
import 'package:schemix/src/generator_api.dart';
import 'package:test/test.dart';
import 'package:zod_schemix_generator/zod_schemix_generator.dart';

// ── Stub TypeGraph ─────────────────────────────────────────────────────────────

final class _StubGraph implements TypeGraph {
  const _StubGraph({required this.enums, required this.models});
  final Set<String> enums;
  final Set<String> models;

  @override
  bool isEnum(String name) => enums.contains(name);
  @override
  bool isModel(String name) => models.contains(name);
  @override
  bool isEmbeddable(String name) => false;
  @override
  TypeInfo? resolve(String name) => models.contains(name)
      ? TypeInfo(name: name, isEnum: false, sourceAssetPath: 'lib/models.dart')
      : null;
  @override
  Set<String> get cyclicTypes => const {};
  @override
  String? relativeImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
  @override
  String? relativeDrizzleImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
}

// ── Fixtures ──────────────────────────────────────────────────────────────────

final _userClass = const ClassInfo(
  name: 'User',
  assetPath: 'lib/models/user.dart',
  hasSchemix: true,
  generators: GeneratorFlags(zod: true),
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      validation: FieldValidation(isUuid: true),
    ),
    FieldInfo(
      name: 'email',
      dartType: 'String',
      isNullable: false,
      validation: FieldValidation(isEmail: true),
    ),
    FieldInfo(
      name: 'score',
      dartType: 'int',
      isNullable: true,
      validation: FieldValidation(min: 0, max: 100),
    ),
  ],
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = ZodGenerator();

  group('ZodGenerator.shouldRun', () {
    test('returns true when generators.zod is true and hasSchemix', () {
      expect(generator.shouldRun(_userClass), isTrue);
    });

    test('returns false when generators.zod is false', () {
      final cls = const ClassInfo(
        name: 'Post',
        assetPath: 'lib/post.dart',
        hasSchemix: true,
        generators: GeneratorFlags(zod: false),
      );
      expect(generator.shouldRun(cls), isFalse);
    });
  });

  group('ZodGenerator.generateForFile — User golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateForFile(
        [_userClass],
        'lib/models/user.dart',
        const _StubGraph(enums: {}, models: {}),
      );
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('exports UserSchema', () {
      expect(output, contains('UserSchema'));
    });

    test('id field has .uuid() validation', () {
      expect(output, contains('.uuid()'));
    });

    test('email field has .email() validation', () {
      expect(output, contains('.email()'));
    });

    test('nullable score field has .nullish()', () {
      expect(output, contains('.nullish()'));
    });

    test('score has min/max bounds', () {
      expect(output, contains('.gte(0)'));
      expect(output, contains('.lte(100)'));
    });

    test('generated header is present', () {
      expect(output, contains('GENERATED BY SCHEMIX'));
    });
  });

  group('ZodGenerator — skipField behaviour', () {
    test('ZodIgnore field is excluded', () {
      final cls = const ClassInfo(
        name: 'Token',
        assetPath: 'lib/token.dart',
        hasSchemix: true,
        generators: GeneratorFlags(zod: true),
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(
            name: 'rawToken',
            dartType: 'String',
            isNullable: false,
            platform: FieldPlatformFlags(zodIgnore: true),
          ),
        ],
      );

      final output = generator.generateForFile(
        [cls],
        'lib/token.dart',
        const _StubGraph(enums: {}, models: {}),
      );

      expect(output, contains('id'));
      expect(output, isNot(contains('rawToken')));
    });

    test('OfflineOnly field is excluded', () {
      final cls = const ClassInfo(
        name: 'Config',
        assetPath: 'lib/config.dart',
        hasSchemix: true,
        generators: GeneratorFlags(zod: true),
        ownFields: [
          FieldInfo(name: 'id', dartType: 'String', isNullable: false),
          FieldInfo(
            name: 'localCache',
            dartType: 'String',
            isNullable: true,
            sync: FieldSyncInfo(offlineOnly: true),
          ),
        ],
      );

      final output = generator.generateForFile(
        [cls],
        'lib/config.dart',
        const _StubGraph(enums: {}, models: {}),
      );

      expect(output, isNot(contains('localCache')));
    });
  });
}
