// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/category/category.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'category.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Category _$CategoryFromJson(Map<String, dynamic> json) =>
    Category(
      id: json['id'] as String,
      name: json['name'] as String,
      type: json['type'] == null ? CategoryType.values.byName('standard') : _$safeByName(CategoryType.values, json['type'] as String, CategoryType.values.byName('standard')),
      posts: (json['posts'] as List<dynamic>).map((e) => Post.fromJson(e as Map<String, dynamic>)).toList(),
    );

Map<String, dynamic> _$CategoryToJson(Category instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'type': instance.type.name,
      'posts': instance.posts.map((e) => e.toJson()).toList(),
    };

Category _$CategoryCopy(Category src) =>
    Category(
      id: src.id,
      name: src.name,
      type: src.type,
      posts: src.posts,
    );
