builders:
  tsBuilder:
    import: "package:ts_schemix_generator/builder.dart"
    builder_factories: ["tsBuilder"]
    build_extensions:
      "lib/$lib$": []
    auto_apply: dependents
    build_to: cache
    required_inputs:
      - "$package$lib/schemix_registry.json"
    runs_before:
      - "schemix_builder|schemix_file"
