// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/tag/tag.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'tag.dart';

Tag _$TagFromJson(Map<String, dynamic> json) =>
    Tag(
      id: json['id'] as String,
      name: json['name'] as String,
      slug: json['slug'] as String,
      posts: (json['posts'] as List<dynamic>).map((e) => PostTag.fromJson(e as Map<String, dynamic>)).toList(),
    );

Map<String, dynamic> _$TagToJson(Tag instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'slug': instance.slug,
      'posts': instance.posts.map((e) => e.toJson()).toList(),
    };

Tag _$TagCopy(Tag src) =>
    Tag(
      id: src.id,
      name: src.name,
      slug: src.slug,
      posts: src.posts,
    );
