// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post/post.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'post.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Post _$PostFromJson(Map<String, dynamic> json) =>
    Post(
      id: json['id'] as String,
    )
      ..title = json['title'] as String?
      ..body = json['body'] as String?
      ..slug = json['slug'] as String?
      ..status = json['status'] == null ? PostStatus.values.byName('draft') : _$safeByName(PostStatus.values, json['status'] as String, PostStatus.values.byName('draft'))
      ..userId = json['userId'] as String?
      ..categoryId = json['categoryId'] as String?
      ..tags = (json['tags'] as List<dynamic>).map((e) => PostTag.fromJson(e as Map<String, dynamic>)).toList();


Map<String, dynamic> _$PostToJson(Post instance) =>
    <String, dynamic>{
      'id': instance.id,
      'title': instance.title,
      'body': instance.body,
      'slug': instance.slug,
      'status': instance.status.name,
      'userId': instance.userId,
      'categoryId': instance.categoryId,
      'tags': instance.tags.map((e) => e.toJson()).toList(),
    };

Post _$PostCopy(Post src) =>
    Post(
      id: src.id,
    )
      ..title = src.title
      ..body = src.body
      ..slug = src.slug
      ..status = src.status
      ..userId = src.userId
      ..categoryId = src.categoryId
      ..tags = src.tags;

