// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/category/category.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example/schemix.dart';

// ─── Category ───────────────────────────────────────────────

@UseRowClass(Category, generateInsertable: true)
class CategoryTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get name => text().named('name')();
  IntColumn get type => integer().named('type').map(CategoryTable.$categoryTypeConverter)();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  static TypeConverter<CategoryType, int> get $categoryTypeConverter =>
      EnumIndexConverter<CategoryType>(CategoryType.values);

  @override
  String get tableName => 'categories';
}