// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/order/order.dart
//
// ignore all

import { integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { users } from '../user/user.drizzle';

export const orders = pgTable('orders', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  userId: text('user_id').references(() => users.id).notNull(),
  status: text('status').default('pending').notNull(),
  orderNumber: integer('order_number'),
  creditCardToken: text('credit_card_token'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const ordersRelations = relations(orders, ({ one }) => ({
  user: one(users, { fields: [orders.userId], references: [users.id] }),
}));

export type OrderRow = typeof orders.$inferSelect;
export type NewOrderRow = typeof orders.$inferInsert;