import 'package:build/build.dart';
import 'package:schemix/models.dart';
import 'package:schemix/src/generator_api.dart';
import 'package:test/test.dart';
import 'package:ts_schemix_generator/ts_schemix_generator.dart';

// ── Stub TypeGraph ─────────────────────────────────────────────────────────────

final class _StubGraph implements TypeGraph {
  const _StubGraph({this.models = const {}, this.enums = const {}});
  final Set<String> models;
  final Set<String> enums;

  @override
  bool isEnum(String name) => enums.contains(name);
  @override
  bool isModel(String name) => models.contains(name);
  @override
  bool isEmbeddable(String name) => false;
  @override
  TypeInfo? resolve(String name) {
    if (models.contains(name)) {
      return TypeInfo(
        name: name,
        isEnum: false,
        sourceAssetPath: 'lib/models.dart',
      );
    }
    return null;
  }

  @override
  Set<String> get cyclicTypes => const {};
  @override
  String? relativeImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;
  @override
  String? relativeDrizzleImportFor({
    required String typeName,
    required String fromSourceAssetPath,
  }) => null;

  @override
  bool canImport(String typeName, String generatorId) => true;
}

// ── Stub BuilderOptions ───────────────────────────────────────────────────────

final class _NoOpOptions implements BuilderOptions {
  const _NoOpOptions();
  @override
  Map<String, dynamic> get config => const {};
  @override
  bool get isRoot => true;
  @override
  BuilderOptions overrideWith(BuilderOptions? other) => BuilderOptions(config);
}

GeneratorContext _makeContext([TypeGraph? graph]) => GeneratorContext(
  typeGraph: graph ?? const _StubGraph(models: {}, enums: {}),
  options: const _NoOpOptions(),
  sourceAssetPath: 'lib/models.dart',
);

// ── Fixtures ──────────────────────────────────────────────────────────────────

const _userClass = ClassInfo(
  name: 'User',
  assetPath: 'lib/user.dart',
  hasSchemix: true,
  ownFields: [
    FieldInfo(
      name: 'id',
      dartType: 'String',
      isNullable: false,
      db: FieldDbInfo(isPrimaryKey: true, autoGenerate: true),
    ),
    FieldInfo(name: 'email', dartType: 'String', isNullable: false),
    FieldInfo(name: 'displayName', dartType: 'String', isNullable: true),
  ],
  ctorParamNames: {'id', 'email'},
);

const _statusEnum = ClassInfo(
  name: 'UserStatus',
  assetPath: 'lib/user.dart',
  hasSchemix: true,
  isEnum: true,
  enumValues: ['active', 'inactive', 'suspended'],
);

// ── Tests ─────────────────────────────────────────────────────────────────────

void main() {
  final generator = TsGenerator();

  group('TsGenerator.id and outputExtensions', () {
    test('id is "ts"', () {
      expect(generator.id, 'ts');
    });

    test('outputExtensions contains .g.ts', () {
      expect(generator.outputExtensions, contains('.g.ts'));
    });
  });

  group('TsGenerator.shouldRun', () {
    test('returns true for @Schemix class with zod enabled', () {
      expect(generator.shouldRun(_userClass), isTrue);
    });

    test('returns true for enum class', () {
      expect(generator.shouldRun(_statusEnum), isTrue);
    });

    test('returns false when zod is disabled for non-enum', () {
      const cls = ClassInfo(
        name: 'Internal',
        assetPath: 'lib/internal.dart',
        hasSchemix: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });

    test('returns false for manualImplementation', () {
      const cls = ClassInfo(
        name: 'Manual',
        assetPath: 'lib/manual.dart',
        hasSchemix: true,
        manualImplementation: true,
      );
      expect(generator.shouldRun(cls), isFalse);
    });
  });

  group('TsGenerator.generateFile — User golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateFile(
        [_userClass],
        'lib/user.dart',
        const _StubGraph(),
      );
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('contains zod import', () {
      expect(output, contains("from 'zod'"));
    });

    test('contains GENERATED header', () {
      expect(output, contains('GENERATED BY SCHEMIX'));
    });

    test('contains interface declaration for User', () {
      expect(output, contains('export interface User'));
    });

    test('id field is typed as string', () {
      expect(output, contains('id: string'));
    });

    test('email field is typed as string', () {
      expect(output, contains('email: string'));
    });

    test('nullable displayName field is optional', () {
      expect(output, contains('displayName?:'));
    });
  });

  group('TsGenerator.generateFile — enum golden', () {
    late String output;

    setUpAll(() {
      output = generator.generateFile(
        [_statusEnum],
        'lib/user.dart',
        const _StubGraph(),
      );
    });

    test('output is non-empty', () {
      expect(output, isNotEmpty);
    });

    test('contains enum schema declaration', () {
      expect(output, contains('UserStatusSchema'));
    });

    test('contains all enum values', () {
      expect(output, contains("'active'"));
      expect(output, contains("'inactive'"));
      expect(output, contains("'suspended'"));
    });

    test('contains TypeScript type export', () {
      expect(output, contains('export type UserStatus'));
    });
  });

  group('TsGenerator.generateFile — mixed classes', () {
    test('produces interface and enum in same file', () {
      final out = generator.generateFile(
        [_statusEnum, _userClass],
        'lib/user.dart',
        const _StubGraph(),
      );
      expect(out, contains('UserStatusSchema'));
      expect(out, contains('export interface User'));
    });
  });

  group('TsGenerator.generateFile — empty output', () {
    test('returns empty string when no class passes shouldRun', () {
      const cls = ClassInfo(
        name: 'Internal',
        assetPath: 'lib/internal.dart',
        hasSchemix: true,
      );
      final out = generator.generateFile(
        [cls],
        'lib/internal.dart',
        const _StubGraph(),
      );
      expect(out, isEmpty);
    });
  });

  group('TsGenerator.generate — per-class output', () {
    test('returns .g.ts key in output map', () {
      final out = generator.generate(_userClass, _makeContext());
      expect(out.outputs.keys, contains('.g.ts'));
    });

    test('output content is non-empty for eligible class', () {
      final out = generator.generate(_userClass, _makeContext());
      expect(out.outputs['.g.ts'], isNotEmpty);
    });

    test('returns empty output for non-eligible class', () {
      const cls = ClassInfo(
        name: 'Internal',
        assetPath: 'lib/internal.dart',
        hasSchemix: true,
      );
      final out = generator.generate(cls, _makeContext());
      final content = out.outputs['.g.ts'];
      expect(content, anyOf(isNull, isEmpty));
    });
  });
}
