// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/product/product.dart
//
// ignore all

import { integer, pgTable, real, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';

export const products = pgTable('products', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  name: text('name').notNull(),
  price: real('price').notNull(),
  stock: integer('stock').default(0).notNull(),
  type: text('type').default('physical').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export type ProductRow = typeof products.$inferSelect;
export type NewProductRow = typeof products.$inferInsert;