// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post_tag/post_tag.dart
//
// ignore all

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { posts } from '../post/post.drizzle';
import { tags } from '../tag/tag.drizzle';

export const postTags = pgTable('post_tags', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  postId: text('post_id').references(() => posts.id).notNull(),
  tagId: text('tag_id').references(() => tags.id).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const postTagsRelations = relations(postTags, ({ one }) => ({
  post: one(posts, { fields: [postTags.postId], references: [posts.id] }),
  tag: one(tags, { fields: [postTags.tagId], references: [tags.id] }),
  post: one(posts, { fields: [postTags.id], references: [posts.postTagId] }),
  tag: one(tags, { fields: [postTags.id], references: [tags.postTagId] }),
}));

export type PostTagRow = typeof postTags.$inferSelect;
export type NewPostTagRow = typeof postTags.$inferInsert;