builders:
  drift_schemix_generator:
    import: "package:drift_schemix_generator/builder.dart"
    builder_factories: ["driftBuilder"]
    build_extensions:
      "^lib/{{}}.dart":
        - "lib/{{}}.table.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "$package$lib/schemix_registry.json"
