import 'package:schemix/schemix.dart';

import 'relations_builder.dart';
import 'table_builder.dart';
import 'utils.dart';

/// Assembles the complete `.drizzle.ts` file content from the pre-computed
/// building blocks.
final class DrizzleFileAssembler {
  const DrizzleFileAssembler(this._tableBuilder, this._relationsBuilder);

  final DrizzleTableBuilder _tableBuilder;
  final DrizzleRelationsBuilder _relationsBuilder;

  String assemble({
    required String assetPath,
    required List<ClassInfo> models,
    required List<ClassInfo> referencedEnums,
    required Set<String> colImports,
    required Map<String, Set<String>> crossFileImports,
    required bool needsUuid,
    required bool needsRelations,
  }) {
    final lines = <String>[
      '// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.',
      '// Source: $assetPath',
      '//',
      '// ignore all',
      '',
      "import { ${(colImports.toList()..sort()).join(', ')} } from 'drizzle-orm/pg-core';",
    ];

    if (needsUuid) {
      lines.add("import { v4 as uuidv4 } from 'uuid';");
    }

    if (needsRelations) {
      lines.add("import { relations } from 'drizzle-orm';");
    }

    if (crossFileImports.isNotEmpty) {
      lines.add('');
      for (final entry
          in crossFileImports.entries.toList()
            ..sort((a, b) => a.key.compareTo(b.key))) {
        lines.add(
          "import { ${(entry.value.toList()..sort()).join(', ')} } from '${entry.key}';",
        );
      }
    }

    lines.add('');

    // Enum const + type blocks.
    for (final enumCls in referencedEnums) {
      lines
        ..addAll(_enumBlock(enumCls))
        ..add('');
    }

    // pgTable blocks.
    for (final cls in models) {
      lines
        ..addAll(_tableBuilder.generateTable(cls))
        ..add('');
    }

    // relations() blocks.
    for (final cls in models) {
      final relBlock = _relationsBuilder.generateRelations(cls);
      if (relBlock.isNotEmpty) {
        lines
          ..addAll(relBlock)
          ..add('');
      }
    }

    // $inferSelect / $inferInsert type exports.
    for (final cls in models) {
      final v = tableVarName(cls.name);
      lines
        ..add('export type ${cls.name}Row = typeof $v.\$inferSelect;')
        ..add('export type New${cls.name}Row = typeof $v.\$inferInsert;');
    }

    return '${lines.join('\n')}\n';
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────

  List<String> _enumBlock(ClassInfo enumCls) => [
    "export const ${enumCls.name.camelCase}Values = [${enumCls.enumValues.map((v) => "'$v'").join(', ')}] as const;",
    "export type ${enumCls.name}Enum = typeof ${enumCls.name.camelCase}Values[number];",
  ];
}
