// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post/post.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example_outfolder/schemix.dart';

// ─── Post ───────────────────────────────────────────────

@UseRowClass(Post, generateInsertable: false)
class PostTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get title => text().named('title').nullable()();
  TextColumn get body => text().named('body').nullable()();
  TextColumn get slug => text().named('slug').nullable()();
  TextColumn get status => text().named('status').map(PostTable.$postStatusConverter)();
  TextColumn get userId => text().named('user_id').references(UserTable, #id).nullable()();
  TextColumn get categoryId => text().named('category_id').references(CategoryTable, #id).nullable()();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  static TypeConverter<PostStatus, String> get $postStatusConverter =>
      EnumNameConverter<PostStatus>(PostStatus.values);

  @override
  String get tableName => 'posts';
}