// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/category/category.dart
//
// ignore all

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { posts } from '../post/post.drizzle';

export const categoryTypeValues = ['standard', 'premium', 'internal'] as const;
export type CategoryTypeEnum = typeof categoryTypeValues[number];

export const categories = pgTable('categories', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  name: text('name').notNull().unique(),
  type: text('type', { enum: categoryTypeValues }).default('standard').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const categoriesRelations = relations(categories, ({ many }) => ({
  posts: many(posts),
}));

export type CategoryRow = typeof categories.$inferSelect;
export type NewCategoryRow = typeof categories.$inferInsert;