// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/profile/profile.dart
//
// ignore all

import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { users } from '../user/user.drizzle';

export const profiles = pgTable('profiles', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  userId: text('user_id').references(() => users.id).notNull(),
  website: text('website'),
  phoneNumber: text('phone_number'),
  isActive: boolean('is_active').default(true).notNull(),
  age: integer('age'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const profilesRelations = relations(profiles, ({ one }) => ({
  user: one(users, { fields: [profiles.userId], references: [users.id] }),
}));

export type ProfileRow = typeof profiles.$inferSelect;
export type NewProfileRow = typeof profiles.$inferInsert;