// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/user/user.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'user.dart';

User _$UserFromJson(Map<String, dynamic> json) =>
    User(
      id: json['id'] as String,
      email: json['email'] as String,
      passwordHash: json['passwordHash'] as String,
      displayName: json['displayName'] as String?,
      posts: (json['posts'] as List<dynamic>).map((e) => Post.fromJson(e as Map<String, dynamic>)).toList(),
      profile: json['profile'] == null ? null : Profile.fromJson(json['profile'] as Map<String, dynamic>),
      metadata: (json['metadata'] as Map<String, dynamic>?)?.cast<String, dynamic>(),
    );

Map<String, dynamic> _$UserToJson(User instance) =>
    <String, dynamic>{
      'id': instance.id,
      'email': instance.email,
      'passwordHash': instance.passwordHash,
      'displayName': instance.displayName,
      'posts': instance.posts.map((e) => e.toJson()).toList(),
      'profile': instance.profile?.toJson(),
      'metadata': instance.metadata,
    };

User _$UserCopy(User src) =>
    User(
      id: src.id,
      email: src.email,
      passwordHash: src.passwordHash,
      displayName: src.displayName,
      posts: src.posts,
      profile: src.profile,
      metadata: src.metadata,
    );
