// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/order/order.dart
//
// ignore_for_file: type=lint

import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import 'package:example/schemix.dart';

// ─── Order ───────────────────────────────────────────────

@UseRowClass(Order, generateInsertable: true)
class OrderTable extends Table {
  TextColumn get id => text().named('id').clientDefault(() => const Uuid().v4())();
  TextColumn get userId => text().named('user_id')();
  TextColumn get status => text().named('status')();
  IntColumn get orderNumber => integer().named('order_number').nullable()();
  TextColumn get creditCardToken => text().named('credit_card_token').nullable()();
  DateTimeColumn get createdAt => dateTime().named('created_at').withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().named('updated_at').withDefault(currentDateAndTime)();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();

  @override
  String get tableName => 'orders';
}