// GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/order/order.dart
//
// ignore_for_file: type=lint, invalid_annotation_target

part of 'order.dart';

T _$safeByName<T extends Enum>(List<T> values, String name, T fallback) {
  try { return values.byName(name); } catch (_) { return fallback; }
}

Order _$OrderFromJson(Map<String, dynamic> json) =>
    Order(
      id: json['id'] as String,
      userId: json['userId'] as String,
      status: json['status'] as String,
      orderNumber: json['orderNumber'] as int?,
    );

Map<String, dynamic> _$OrderToJson(Order instance) =>
    <String, dynamic>{
      'id': instance.id,
      'userId': instance.userId,
      'status': instance.status,
      'creditCardToken': instance.creditCardToken,
    };

Order _$OrderCopy(Order src) =>
    Order(
      id: src.id,
      userId: src.userId,
      status: src.status,
      orderNumber: src.orderNumber,
      creditCardToken: src.creditCardToken,
    );
