// AUTO-GENERATED BY SCHEMIX — DO NOT EDIT.
// Source: lib/models/post/post.dart
//
// ignore all

import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { relations } from 'drizzle-orm';

import { categories } from '../category/category.drizzle';
import { tags } from '../tag/tag.drizzle';
import { users } from '../user/user.drizzle';

export const postStatusValues = ['draft', 'published', 'archived'] as const;
export type PostStatusEnum = typeof postStatusValues[number];

export const posts = pgTable('posts', {
  id: text('id').$defaultFn(() => uuidv4()).primaryKey(),
  title: text('title'),
  body: text('body'),
  slug: text('slug'),
  status: text('status', { enum: postStatusValues }).default('draft').notNull(),
  userId: text('user_id'),
  categoryId: text('category_id'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const postsRelations = relations(posts, ({ one, many }) => ({
  userId: one(users, { fields: [posts.userId], references: [users.id] }),
  categoryId: one(categories, { fields: [posts.categoryId], references: [categories.id] }),
  tags: many(tags),
}));

export type PostRow = typeof posts.$inferSelect;
export type NewPostRow = typeof posts.$inferInsert;