abstract final class SerializableHeader {
  SerializableHeader._();

  static String build(String assetPath) {
    final partOf = assetPath.replaceAll('\\', '/').split('/').last;
    return [
      '// GENERATED BY SCHEMIX — DO NOT EDIT.',
      '// Source: $assetPath',
      '//',
      '// ignore_for_file: type=lint, invalid_annotation_target',
      '',
      "part of '$partOf';",
      '',
      'T _\$safeByName<T extends Enum>('
          'List<T> values, String name, T fallback) {',
      '  try { return values.byName(name); } catch (_) { return fallback; }',
      '}',
    ].join('\n');
  }
}
