abstract final class SerializableHeader {
  SerializableHeader._();

  static String build(String assetPath, {bool usesEnum = false}) {
    final partOf = assetPath.replaceAll('\\', '/').split('/').last;
    final header = [
      '// GENERATED BY SCHEMIX — DO NOT EDIT.',
      '// Source: $assetPath',
      '//',
      '// ignore_for_file: type=lint, invalid_annotation_target',
      '',
      "part of '$partOf';",
    ];
    if (usesEnum) {
      header.addAll([
        '',
        'T _\$safeByName<T extends Enum>('
            'List<T> values, String name, T fallback) {',
        '  try { return values.byName(name); } catch (_) { return fallback; }',
        '}',
      ]);
    }
    return header.join('\n');
  }
}
