import 'dart:async';

import 'package:build/build.dart';
import 'package:path/path.dart' as p;

import 'package:schemix_builder/schemix_builder.dart';

Builder driftBarrelBuilder(BuilderOptions options) =>
    _SchemixDriftBarrelBuilder(options);

final class _SchemixDriftBarrelBuilder implements Builder {
  _SchemixDriftBarrelBuilder(BuilderOptions options)
      : _outputDir = options.config['output_dir'] as String? ?? 'lib',
        _outputFile = options.config['output_file'] as String? ?? 'tables.drift',
        _driftSuffix = options.config['drift_suffix'] as String? ?? '.table.dart';

  final String _outputDir;
  final String _outputFile;
  final String _driftSuffix;

  static final _log = const SchemixLogger('drift_barrel');

  @override
  Map<String, List<String>> get buildExtensions => {
        r'$package$': ['$_outputDir/$_outputFile'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final outputs = buildStep.allowedOutputs.toList();
    if (outputs.isEmpty) {
      _log.buildSkip('$_outputDir/$_outputFile', 'no allowed outputs');
      return;
    }

    final barrelId = outputs.first;

    final registryId = AssetId(buildStep.inputId.package, 'lib/schemix_registry.json');
    if (!await buildStep.canRead(registryId)) {
      _log.buildSkip(barrelId.path, 'schemix_registry.json not found');
      return;
    }

    final registryContent = await buildStep.readAsString(registryId);
    final registry = CrossFileRegistry.fromJson(registryContent);

    final modelPaths = <String>{};
    for (final typeInfo in registry.allModels) {
      if (!typeInfo.manualImplementation) {
        modelPaths.add(typeInfo.sourceAssetPath);
      }
    }

    if (modelPaths.isEmpty) {
      _log.buildSkip(barrelId.path, 'no models found in registry');
      return;
    }

    final sortedModels = modelPaths.toList()..sort();

    final buf = StringBuffer();
    buf.writeln('/* GENERATED BY SCHEMIX — DO NOT EDIT. */');
    buf.writeln('/* Drift barrel re-export of all schemix tables. */');
    buf.writeln();

    for (final path in sortedModels) {
      final rel = p.relative(path, from: _outputDir);
      final importPath = rel.replaceAll(r'\', '/');
      final withoutExt = importPath.substring(0, importPath.length - 5);
      buf.writeln("import '$withoutExt$_driftSuffix';");
    }

    await buildStep.writeAsString(barrelId, buf.toString());
    _log.outputWrite(barrelId.path, 'DriftBarrelBuilder');
  }
}
