/// Assembles the file-level comment block and import statements that appear at
/// the top of every generated `.table.dart` file.
final class DriftHeader {
  const DriftHeader({this.modelsPackage = 'models'});

  /// The Dart package name that exports the user's model classes.
  /// Defaults to `'models'`; configurable via `build.yaml` options as
  /// `models_package`.
  final String modelsPackage;

  /// Returns the header lines for a file that was generated from [assetPath].
  List<String> build(String assetPath) => [
    '// GENERATED BY SCHEMIX — DO NOT EDIT.',
    '// Source: $assetPath',
    '//',
    '// ignore_for_file: type=lint',
    '',
    "import 'package:drift/drift.dart';",
    "import 'package:uuid/uuid.dart';",
    "import 'package:$modelsPackage/$modelsPackage.dart';",
    '',
    '',
  ];
}
