builders:
  serializable_schemix_generator:
    import: "package:serializable_schemix_generator/builder.dart"
    builder_factories: ["serializableBuilder"]
    build_extensions:
      "^lib/{{}}.dart":
        - "lib/{{}}.schemix.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "$package$lib/schemix_registry.json"
