builders:
  serializable_schemix_generator:
    import: "package:serializable_schemix_generator/serializable_schemix_generator.dart"
    builder_factories: ["serializableBuilder"]
    build_extensions:
      ".dart":
        - ".schemix.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "$package$lib/schemix_registry.json"